@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Blanca",
    "nameTwo":"Pam",
    "date":"11/11/2023",
    "time":"14:00",
    "contactOne":"pancho",
    "contactTwo":"",
    "contactThree":"",
    "locationOne":"fiesta",
    "locationTwo":"",
    "locationThree":"",
    "message":"1234"
}

####
GET {{baseUrl}}/{{urlPath}}/event/640dda7dea0e41c33be19242
Content-Type: application/json
Accept: application/json
withCredentials: true

####
DELETE {{baseUrl}}/{{urlPath}}/event/640f41b9cc0b3f8888a045ba
Content-Type: application/json
Accept: application/json
withCredentials: true

####
PUT {{baseUrl}}/{{urlPath}}/event/640f0604cb41cf5209f91e5b
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Blanca",
    "nameTwo":"Pam",
    "date":"11/11/2023",
    "time":"14:00",
    "contactOne":"Juan",
    "contactTwo":"Maria",
    "contactThree":"otromas",
    "locationOne":"fiesta",
    "locationTwo":"Ceremonia religiosa",
    "locationThree":"",
    "message":"1234"
}