@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Blanca",
    "nameTwo":"Pam",
    "date":"11/11/2023",
    "time":"14:00",
    "contactOne":
        {
        "title":"Dama de honor",
        "name":"Erika",
        "phone":"477 117 4589",
        "inChargeOf":"Logistica"
        },
    "contactTwo":
       {
        "title":"Mejor amigo",
        "name":"Juan",
        "phone":"477 117 4589",
        "inChargeOf":""
        },
    "contactThree":{},
    "locationOne":
       {
        "title":"Ceremonia religiosa",
        "name":"Iglesia de la parroquia",
        "image":"",
        "date":"21/05/2023",
        "time":"14:00",
        "address":"Calle 50 Centro"
        },
    "locationTwo": {
        "title":"Festejo",
        "name":"",
        "image":"",
        "date":"21/05/2023",
        "time":"17:00",
        "address":"Calle 1250 Centro"
        },
    "locationThree":{},
    "message":"1234"
}

####
GET {{baseUrl}}/{{urlPath}}/event/640f403ebab693c08cfd9ffe
Content-Type: application/json
Accept: application/json
withCredentials: true

####
DELETE {{baseUrl}}/{{urlPath}}/event/640f41b9cc0b3f8888a045ba
Content-Type: application/json
Accept: application/json
withCredentials: true

####
PUT {{baseUrl}}/{{urlPath}}/event/640f0604cb41cf5209f91e5b
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Blanca",
    "nameTwo":"Pam",
    "date":"11/11/2023",
    "time":"14:00",
    "contactOne":"Juan",
    "contactTwo":"Maria",
    "contactThree":"otromas",
    "locationOne":"fiesta",
    "locationTwo":"Ceremonia religiosa",
    "locationThree":"",
    "message":"1234"
}