@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Jorge",
    "nameTwo":"Ziska",
    "date":"29/02/2023",
    "time":"14:00",
    "contact":
    [
        {
        "title":"Dama de honor",
        "name":"Erika",
        "phone":"477 117 4589",
        "inChargeOf":"Logistica"
        },
       {
        "title":"Mejor amigo",
        "name":"Juan",
        "phone":"477 117 4589",
        "inChargeOf":""
        }
    ],
    "locations":
    [
       {
        "title":"Ceremonia religiosa",
        "name":"Iglesia de la parroquia",
        "image":"",
        "date":"21/05/2023",
        "time":"14:00",
        "address":"Calle 50 Centro"
        },
  	    {
        "title":"Festejo",
        "name":"",
        "image":"",
        "date":"21/05/2023",
        "time":"17:00",
        "address":"Calle 1250 Centro"
        },
        {
        "title":"Festejo",
        "name":"",
        "image":"",
        "date":"21/05/2023",
        "time":"17:00",
        "address":"Calle 1250 Centro"
        }
    ],
    "message":"save the date",
    "image":"image",
    "menus":["vegetariano", "con carne"],
    "gifts":["liverpool", "amazon wishlist"],
    "childPolicy": false,
    "dressCode": "Playero"
}

####
GET {{baseUrl}}/{{urlPath}}/event/641a107e4cd2c302066e93af
Content-Type: application/json
Accept: application/json
withCredentials: true


####
DELETE {{baseUrl}}/{{urlPath}}/event/641a107e4cd2c302066e93af
Content-Type: application/json
Accept: application/json
withCredentials: true

####
PUT {{baseUrl}}/{{urlPath}}/event/654783efe5da298f89cff2c3
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "title":"boda",
    "nameOne":"Jorge",
    "nameTwo":"Yiska",
    "date":"11/11/2023",
    "time":"14:00",
    "contact":
    [
        {
            "id":15648614,
        "title":"Dama de honor",
        "name":"Erika",
        "phone":"477 117 4589",
        "inChargeOf":"Logistica"
        },
       {
        "id":15648624,
        "title":"Mejor amigo",
        "name":"Juan",
        "phone":"477 117 4589",
        "inChargeOf":""
        }
    ],
    "locations":
    [
       {
        "id":15648664,
        "title":"Ceremonia religiosa",
        "name":"Iglesia de la parroquia",
        "image":"",
        "date":"21/05/2023",
        "time":"14:00",
        "address":"Calle 50 Centro"
        },
  	    {"id":15648663,
        "title":"Festejo",
        "name":"",
        "image":"",
        "date":"21/05/2023",
        "time":"17:00",
        "address":"Calle 1250 Centro"
        },
        {
            "id":15648662,
        "title":"Festejo",
        "name":"",
        "image":"",
        "date":"21/05/2023",
        "time":"17:00",
        "address":"Calle 1250 Centro"
        }
    ],
     "message":"save the date",
    "image":"photo",
    "gifts":["liverpool.com", "amazon/wishList.com"],
    "dressCode":["formal"],
    "childPolicy":false
}