@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event/family/641a107e4cd2c302066e93af
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "guests": [{
        "name":"jorge",
        "surname":"Rodriguez"
    }, 
     {
        "name":"ziska",
        "surname":"hammerl"
    }],
    "extraGuestPermission":true
}

####
GET {{baseUrl}}/{{urlPath}}/event/confirmation/6453ea1a3452fcf2598143c7
Content-Type: application/json
Accept: application/json
withCredentials: true
