@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event/family/654fea041301eecb58d5c3a0
Content-Type: application/json
Accept: application/json
withCredentials: true

[
    {
        "guests": [
            {
                "name":"jorge",
                "surname":"Rodriguez"
            }, 
            {
                "name":"ziska",
                "surname":"hammerl"
            }
        ],
        "extraGuestPermission":true
    }
]

####
GET {{baseUrl}}/{{urlPath}}/event/confirmation/654fea041301eecb58d5c3a0/654fefb40e7b7e8aab0b4476
Content-Type: application/json
Accept: application/json
withCredentials: true
