@baseUrl = http://localhost:9090
@urlPath = api/v1


####
GET {{baseUrl}}/{{urlPath}}/event/guestlist/6415f542495ba3019fb9e5da
Content-Type: application/json
Accept: application/json
withCredentials: true

####
POST {{baseUrl}}/{{urlPath}}/event/confirmation/641a107e4cd2c302066e93af/6415f542495ba3019fb9e5da
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "guests": [{
        "name":"jorge",
        "surname":"Rodriguez",
        "status":true,
        "menu":"vegetariano"
    },
    {
        "name":"Ziska",
        "surname":"Hammerl",
        "status":true,   
        "menu":"meat"
    }, 
    {
        "name":"Lotti",
        "surname":"Rodriguez",
        "status":true,   
        "menu":"meat"
    }
]
}

####
PUT {{baseUrl}}/{{urlPath}}/event/confirmation/641a107e4cd2c302066e93af/6453ea1a3452fcf2598143c7
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "guests": [{
        "name":"luis",
        "surname":"Rodriguez",
        "status":true,
        "menu":"vegetariano",
        "_id":"6412244a452759b54141c1f5"
    },
    {
        "name":"neli",
        "surname":"Hammerl",
        "status":true,   
        "menu":"vegetariano",
        "_id":"6412244a452759b54141c1f9"
    }, 
    {
        "name":"Lotti",
        "surname":"Rodriguez",
        "status":true,   
        "menu":"vegetariano",
        "_id":"6412244a452759b54141c1fe"
    }
]
}

####
DELETE {{baseUrl}}/{{urlPath}}/event/guest/640f52f5999d65a91625eada
Content-Type: application/json
Accept: application/json
withCredentials: true

####
GET {{baseUrl}}/{{urlPath}}/event/guestList/641a107e4cd2c302066e93af
Content-Type: application/json
Accept: application/json
withCredentials: true