@baseUrl = http://localhost:9090
@urlPath = api/v1

####
POST {{baseUrl}}/{{urlPath}}/event/confirmation/640f4343dcc1e4ceaeb1e248/6410bed1042d867465cb1fae
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "guests": [{
        "name":"jorge",
        "surname":"Rodriguez",
        "status":false,
        "menu":"vegetariano"
    },
    {
        "name":"Ziska",
        "surname":"Hammerl",
        "status":true,   
        "menu":"meat"
    }, 
    {
        "name":"Lotti",
        "surname":"Rodriguez",
        "status":true,   
        "menu":"meat"
    }
]
}

####
PUT {{baseUrl}}/{{urlPath}}/event/confirmation/640f4343dcc1e4ceaeb1e248/6410bed1042d867465cb1fae
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "guests": [{
        "name":"jorge",
        "surname":"Rodriguez",
        "status":true,
        "menu":"vegetariano",
        "_id":"64121b330a8a1692e72efb60"
    },
    {
        "name":"Ziska",
        "surname":"Hammerl",
        "status":true,   
        "menu":"vegetariano",
        "_id":"64121b330a8a1692e72efb65"
    }, 
    {
        "name":"Lotti",
        "surname":"Rodriguez",
        "status":true,   
        "menu":"vegetariano",
        "_id":"64121b330a8a1692e72efb6a"
    }
]
}

####
DELETE {{baseUrl}}/{{urlPath}}/event/guest/640f52f5999d65a91625eada
Content-Type: application/json
Accept: application/json
withCredentials: true

####
GET {{baseUrl}}/{{urlPath}}/event/guest/list
Content-Type: application/json
Accept: application/json
withCredentials: true